### PR TITLE
Keep human-step projects at the accept gate

### LINKED ISSUE #145: A project that carried a human step always reaches the accept gate
Part of #89 (its ticket 8) — read #89 first. Depends on #138 (the marker, which is how carried is detected) — do not start until it lands.

## What to build

Nate's call, and an explicit amendment to #51's outcome rather than a reading of it: #51 narrowed the accept gate to New and Replace; this adds one condition — a project that ever carried a human-step ticket stops for acceptance whatever its class. His reasoning: the cases where he personally did part of the work are exactly the ones where it-merged is weakest evidence that it works. carried means ever carried, including tickets closed long since — otherwise the gate can be satisfied by closing the human step first and merging after.

Reconcile with #56 in one pass, not as two assumptions about each other's rules: #56 is blocked on #89, and this amends what #56 builds.

## How to tell it worked

Tests: a Broken, Maintenance, or Improve project that carried a human-step ticket still stops for acceptance; a project of the same classes that never carried one closes as #51/#56 say. The #138 marker is the detection signal — no second record of carried.

## Scope

The accept-gate condition and its tests. The marker is #138's; #56's auto-close is read, not rewritten, except where the reconciliation requires it — and then stated, not assumed.

Risk: escalated — gate change (this widens the accept path)

### PR DESCRIPTION
**Pull request by nateprich**
## Summary

- derive whether a project ever carried a human-step ticket from the canonical child marker after the complete Project feed has loaded
- keep that history after the human-step ticket closes, without adding a second persisted record
- reconcile the accept-gate split with #56: New, Replace, and unset classes still ask; Broken, Maintenance, and Improve ask only when they carried a human step

## Sequencing

This branch started fresh from main; there was no prior ticket/145 branch or pull request. It implements the combined gate condition #145 says #56 must consume. It does not implement #55's merge-time auto-close write.

## Verification

- `python3 -m pytest tests/test_ordering.py tests/test_human_step.py tests/test_brief.py tests/test_rendering.py -q` — 110 passed
- `python3 -m pytest -q -k 'not test_every_codex_automation_matches_the_routine'` — 521 passed, 1 deselected
- the unfiltered suite has the same single installed-machine drift failure tracked by #163: four Codex schedules do not match `routines/codex-work.md`
- a live `funnel brief` read could not run because GitHub's GraphQL rate limit was exhausted; no runtime claim is made from that check

Closes #145

### CODE REVIEW

**Comment by nateprich** [comment]
**Review: approved** (CI green)

```json
{
  "blocking": [],
  "ci": "green",
  "head_sha": "02250cdefc5a07f7ab5a749d210b49bb76cab053",
  "reviewed_at": "2026-09-09T06:19:14.442207+00:00",
  "verdict": "approved"
}
```



```json
{
  "agent": null,
  "at": "2026-09-09T06:19:16.322666+00:00",
  "run": null,
  "voice": "agent"
}
```
